# Generated by Django 5.0.3 on 2024-04-21 13:31

from django.db import migrations,models


class Migration(migrations.Migration):
    dependencies = [
        ("app","0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelIntroduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name",models.CharField(max_length=100)),
                ("description",models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="UserInfo",
        ),
    ]
