# Generated by Django 5.0.3 on 2024-04-21 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app","0002_modelintroduction_delete_userinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModelIntroduction",
        ),
    ]
