# Generated by Django 5.0.3 on 2024-04-26 03:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app","0005_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
