# Generated by Django 5.0.3 on 2024-04-26 17:20

from django.db import migrations,models

import app.models


class Migration(migrations.Migration):
    dependencies = [
        ("app","0010_modelfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelfile",
            name="file",
            field=models.FileField(upload_to=app.models.get_upload_model_path),
        ),
    ]
