# Generated by Django 5.0.4 on 2024-04-29 19:08

from django.db import migrations,models


class Migration(migrations.Migration):
    dependencies = [
        ("app","0013_imgfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelfile",
            name="classes",
            field=models.TextField(default=""),
        ),
    ]
