# Generated by Django 5.0.4 on 2025-10-22 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations,models

import app.models


class Migration(migrations.Migration):
    dependencies = [
        ("app","0014_modelfile_classes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file",models.FileField(upload_to=app.models.get_upload_pdf_path)),
                ("file_name",models.CharField(max_length=255)),
                ("file_size",models.IntegerField(default=0)),
                ("uploaded_at",models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
